var GoogleSitesDialog = function(b, e) {
  function f() {
    var q = null != l && null != l.getTitle() ? l.getTitle() : this.defaultFilename;
    if (F.checked && '' != G.value) {
      var A = 'https://www.draw.io/gadget.xml?type=4&diagram=' + encodeURIComponent(mxUtils.htmlEntities(G.value));
      null != q && (A += '&title=' + encodeURIComponent(q));
      0 < L.length && (A += '&s=' + L);
      '' != d.value && '0' != d.value && (A += '&border=' + d.value);
      '' != J.value && (A += '&height=' + J.value);
      A += '&pan=' + (g.checked ? '1' : '0');
      A += '&zoom=' + (n.checked ? '1' : '0');
      A += '&fit=' + (C.checked ? '1' : '0');
      A += '&resize=' + (x.checked ? '1' : '0');
      A += '&x0=' + Number(D.value);
      A += '&y0=' + E;
      k.mathEnabled && (A += '&math=1');
      u.checked ? A += '&edit=_blank' : v.checked && (A += '&edit=' + encodeURIComponent(mxUtils.htmlEntities(window.location.href)));
      z.value = A;
    } else
      l.constructor == DriveFile || l.constructor == DropboxFile ? (A = 'https://www.draw.io/gadget.xml?embed=0&diagram=', '' != G.value ? A += encodeURIComponent(mxUtils.htmlEntities(G.value)) + '&type=3' : (A += l.getHash().substring(1), A = l.constructor == DropboxFile ? A + '&type=2' : A + '&type=1'), null != q && (A += '&title=' + encodeURIComponent(q)), '' != J.value && (q = parseInt(J.value) + parseInt(D.value), A += '&height=' + q), z.value = A) : z.value = '';
  }
  var c = document.createElement('div'),
    k = b.editor.graph,
    m = k.getGraphBounds(),
    t = k.view.scale,
    y = Math.floor(m.x / t - k.view.translate.x),
    E = Math.floor(m.y / t - k.view.translate.y);
  mxUtils.write(c, mxResources.get('googleGadget') + ':');
  mxUtils.br(c);
  var z = document.createElement('input');
  z.setAttribute('type', 'text');
  z.style.marginBottom = '8px';
  z.style.marginTop = '2px';
  z.style.width = '410px';
  c.appendChild(z);
  mxUtils.br(c);
  this.init = function() {
    z.focus();
    mxClient.IS_GC || mxClient.IS_FF || 5 <= document.documentMode ? z.select() : document.execCommand('selectAll', !1, null);
  };
  mxUtils.write(c, mxResources.get('top') + ':');
  var D = document.createElement('input');
  D.setAttribute('type', 'text');
  D.setAttribute('size', '4');
  D.style.marginRight = '16px';
  D.style.marginLeft = '4px';
  D.value = y;
  c.appendChild(D);
  mxUtils.write(c, mxResources.get('height') + ':');
  var J = document.createElement('input');
  J.setAttribute('type', 'text');
  J.setAttribute('size', '4');
  J.style.marginLeft = '4px';
  J.value = Math.ceil(m.height / t);
  c.appendChild(J);
  mxUtils.br(c);
  m = document.createElement('hr');
  m.setAttribute('size', '1');
  m.style.marginBottom = '16px';
  m.style.marginTop = '16px';
  c.appendChild(m);
  mxUtils.write(c, mxResources.get('publicDiagramUrl') + ':');
  mxUtils.br(c);
  var G = document.createElement('input');
  G.setAttribute('type', 'text');
  G.setAttribute('size', '28');
  G.style.marginBottom = '8px';
  G.style.marginTop = '2px';
  G.style.width = '410px';
  G.value = e || '';
  c.appendChild(G);
  mxUtils.br(c);
  mxUtils.write(c, mxResources.get('borderWidth') + ':');
  var d = document.createElement('input');
  d.setAttribute('type', 'text');
  d.setAttribute('size', '3');
  d.style.marginBottom = '8px';
  d.style.marginLeft = '4px';
  d.value = '0';
  c.appendChild(d);
  mxUtils.br(c);
  var g = document.createElement('input');
  g.setAttribute('type', 'checkbox');
  g.setAttribute('checked', 'checked');
  g.defaultChecked = !0;
  g.style.marginLeft = '16px';
  c.appendChild(g);
  mxUtils.write(c, mxResources.get('pan') + ' ');
  var n = document.createElement('input');
  n.setAttribute('type', 'checkbox');
  n.setAttribute('checked', 'checked');
  n.defaultChecked = !0;
  n.style.marginLeft = '8px';
  c.appendChild(n);
  mxUtils.write(c, mxResources.get('zoom') + ' ');
  var v = document.createElement('input');
  v.setAttribute('type', 'checkbox');
  v.style.marginLeft = '8px';
  v.setAttribute('title', window.location.href);
  c.appendChild(v);
  mxUtils.write(c, mxResources.get('edit') + ' ');
  var u = document.createElement('input');
  u.setAttribute('type', 'checkbox');
  u.style.marginLeft = '8px';
  c.appendChild(u);
  mxUtils.write(c, mxResources.get('asNew') + ' ');
  mxUtils.br(c);
  var x = document.createElement('input');
  x.setAttribute('type', 'checkbox');
  x.setAttribute('checked', 'checked');
  x.defaultChecked = !0;
  x.style.marginLeft = '16px';
  c.appendChild(x);
  mxUtils.write(c, mxResources.get('resize') + ' ');
  var C = document.createElement('input');
  C.setAttribute('type', 'checkbox');
  C.style.marginLeft = '8px';
  c.appendChild(C);
  mxUtils.write(c, mxResources.get('fit') + ' ');
  var F = document.createElement('input');
  F.setAttribute('type', 'checkbox');
  F.style.marginLeft = '8px';
  c.appendChild(F);
  mxUtils.write(c, mxResources.get('embed') + ' ');
  var L = b.getBasenames().join(';'),
    l = b.getCurrentFile();
  mxEvent.addListener(g, 'change', f);
  mxEvent.addListener(n, 'change', f);
  mxEvent.addListener(x, 'change', f);
  mxEvent.addListener(C, 'change', f);
  mxEvent.addListener(v, 'change', f);
  mxEvent.addListener(u, 'change', f);
  mxEvent.addListener(F, 'change', f);
  mxEvent.addListener(J, 'change', f);
  mxEvent.addListener(D, 'change', f);
  mxEvent.addListener(d, 'change', f);
  mxEvent.addListener(G, 'change', f);
  f();
  mxEvent.addListener(z, 'click', function() {
    z.focus();
    mxClient.IS_GC || mxClient.IS_FF || 5 <= document.documentMode ? z.select() : document.execCommand('selectAll', !1, null);
  });
  e = document.createElement('div');
  e.style.paddingTop = '12px';
  e.style.textAlign = 'right';
  m = mxUtils.button(mxResources.get('close'), function() {
    b.hideDialog();
  });
  m.className = 'geBtn gePrimaryBtn';
  e.appendChild(m);
  c.appendChild(e);
  this.container = c;
};